
BINS= test.elf #motor_tester.elf

OBJS= ../avr_common/uart_int.o #./my_librarys/encoder.o  ./my_librarys/pwm_signal.o ./my_librarys/digital_io.o ./my_librarys/timer.o  ./my_librarys/Motor.o

HEADERS= ../avr_common/uart_int.h #./my_librarys/encoder.h ./my_librarys/pwm_signal.h  ./my_librarys/digital_io.h  ./my_librarys/timer.h  ./my_librarys/Motor.h

include ../avr_common/avr_geo.mk
