
BINS= motor_tester.elf

OBJS=  ./my_librarys/uart_int.o ./my_librarys/encoder.o  ./my_librarys/pwm_signal.o ./my_librarys/digital_io.o ./my_librarys/timer.o  ./my_librarys/Motor.o #../avr_common/uart.o

HEADERS=  ./my_librarys/uart_int.h ./my_librarys/encoder.h ./my_librarys/pwm_signal.h  ./my_librarys/digital_io.h  ./my_librarys/timer.h  ./my_librarys/Motor.h #../avr_common/uart.h

include ../avr_common/avr_geo.mk
