
BINS=encoder_reader.elf

OBJS=./librarys/uart.o ./my_librarys/encoder.o  ./my_librarys/pwm_signal.o ./my_librarys/digital_io.o

HEADERS=./librarys/uart.h ./my_librarys/encoder.h ./my_librarys/pwm_signal.h  ./my_librarys/digital_io.h 

include ../avr_common/avr.mk
